#!/bin/sh

if [ "$1" != 'origin' ]
then
	echo 'push origin'
#	git push origin -f --mirror --no-verify
fi
if [ "$1" != 'mirror1' ]
then
	echo 'push mirror1'
#	git push mirror1 -f --mirror --no-verify
fi

echo "push $1"
