#!/bin/bash

remotes=( $(git remote) )

for it in "${remotes[@]}"
do
	if [ "$1" != "$it" ]
	then
		branch=()
		while read local_ref local_sha remote_ref remote_sha
		do
			branch+=( $(echo $remote_ref | sed -e 's,.*/\(.*\),\1,') )
			git push "$it ${branch[*]}" -f --mirror --no-verify
		done
	fi
done
